"""initial schema

Revision ID: 6bb7cbc6242e
Revises: 
Create Date: 2026-07-14 07:31:09.714374

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0001'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('parking_areas',
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('code', sa.String(length=20), nullable=False),
    sa.Column('zone_description', sa.String(length=500), nullable=True),
    sa.Column('capacity', sa.Integer(), nullable=False),
    sa.Column('occupied_slots', sa.Integer(), nullable=False),
    sa.Column('map_x', sa.Float(), nullable=False),
    sa.Column('map_y', sa.Float(), nullable=False),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('current_risk_level', sa.Enum('SAFE', 'MODERATE', 'UNSAFE', name='risklevel'), nullable=False),
    sa.Column('current_risk_score', sa.Float(), nullable=False),
    sa.Column('is_closed', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_index(op.f('ix_parking_areas_id'), 'parking_areas', ['id'], unique=False)
    op.create_table('users',
    sa.Column('full_name', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('role', sa.Enum('ADMIN', 'SAFETY_OFFICER', 'FACTORY_MANAGER', 'SECURITY_GUARD', 'EMPLOYEE', 'ENVIRONMENTAL_OFFICER', name='userrole'), nullable=False),
    sa.Column('phone_number', sa.String(length=32), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_superuser', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_table('weather_records',
    sa.Column('source', sa.String(length=50), nullable=False),
    sa.Column('temperature', sa.Float(), nullable=True),
    sa.Column('humidity', sa.Float(), nullable=True),
    sa.Column('wind_speed', sa.Float(), nullable=True),
    sa.Column('wind_direction', sa.Float(), nullable=True),
    sa.Column('rain_mm', sa.Float(), nullable=True),
    sa.Column('pressure_hpa', sa.Float(), nullable=True),
    sa.Column('forecast_summary', sa.String(length=255), nullable=True),
    sa.Column('recorded_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_weather_records_id'), 'weather_records', ['id'], unique=False)
    op.create_index(op.f('ix_weather_records_recorded_at'), 'weather_records', ['recorded_at'], unique=False)
    op.create_table('analytics_rollups',
    sa.Column('parking_area_id', sa.UUID(), nullable=False),
    sa.Column('period_type', sa.String(length=20), nullable=False),
    sa.Column('period_start', sa.Date(), nullable=False),
    sa.Column('avg_co', sa.Float(), nullable=True),
    sa.Column('avg_no2', sa.Float(), nullable=True),
    sa.Column('avg_co2', sa.Float(), nullable=True),
    sa.Column('max_smoke', sa.Float(), nullable=True),
    sa.Column('avg_pm25', sa.Float(), nullable=True),
    sa.Column('unsafe_hours', sa.Float(), nullable=False),
    sa.Column('moderate_hours', sa.Float(), nullable=False),
    sa.Column('safe_hours', sa.Float(), nullable=False),
    sa.Column('total_alerts', sa.Integer(), nullable=False),
    sa.Column('environmental_score', sa.Float(), nullable=True),
    sa.Column('estimated_carbon_kg', sa.Float(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['parking_area_id'], ['parking_areas.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('parking_area_id', 'period_type', 'period_start', name='uq_rollup_period')
    )
    op.create_index(op.f('ix_analytics_rollups_id'), 'analytics_rollups', ['id'], unique=False)
    op.create_index(op.f('ix_analytics_rollups_parking_area_id'), 'analytics_rollups', ['parking_area_id'], unique=False)
    op.create_table('audit_logs',
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('action', sa.String(length=100), nullable=False),
    sa.Column('resource_type', sa.String(length=100), nullable=False),
    sa.Column('resource_id', sa.String(length=100), nullable=True),
    sa.Column('detail', sa.String(length=1000), nullable=True),
    sa.Column('ip_address', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_logs_created_at'), 'audit_logs', ['created_at'], unique=False)
    op.create_index(op.f('ix_audit_logs_id'), 'audit_logs', ['id'], unique=False)
    op.create_table('predictions',
    sa.Column('parking_area_id', sa.UUID(), nullable=False),
    sa.Column('horizon_minutes', sa.Integer(), nullable=False),
    sa.Column('model_name', sa.String(length=100), nullable=False),
    sa.Column('predicted_co', sa.Float(), nullable=True),
    sa.Column('predicted_co2', sa.Float(), nullable=True),
    sa.Column('predicted_no2', sa.Float(), nullable=True),
    sa.Column('predicted_smoke', sa.Float(), nullable=True),
    sa.Column('predicted_pm25', sa.Float(), nullable=True),
    sa.Column('predicted_risk_level', sa.Enum('SAFE', 'MODERATE', 'UNSAFE', name='risklevel'), nullable=False),
    sa.Column('predicted_risk_score', sa.Float(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('generated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('target_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['parking_area_id'], ['parking_areas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_predictions_generated_at'), 'predictions', ['generated_at'], unique=False)
    op.create_index(op.f('ix_predictions_id'), 'predictions', ['id'], unique=False)
    op.create_index(op.f('ix_predictions_parking_area_id'), 'predictions', ['parking_area_id'], unique=False)
    op.create_table('recommendations',
    sa.Column('parking_area_id', sa.UUID(), nullable=False),
    sa.Column('action', sa.Enum('PARK_HERE', 'OPEN_VENTILATION', 'DELAY_ENTRY', 'CLOSE_PARKING', 'ACTIVATE_EXHAUST', 'EVACUATE', name='recommendationaction'), nullable=False),
    sa.Column('rank', sa.Integer(), nullable=False),
    sa.Column('risk_score', sa.Float(), nullable=False),
    sa.Column('exposure_score', sa.String(length=50), nullable=False),
    sa.Column('confidence_score', sa.Float(), nullable=False),
    sa.Column('air_quality_score', sa.Float(), nullable=False),
    sa.Column('explanation', sa.Text(), nullable=False),
    sa.Column('model_version', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['parking_area_id'], ['parking_areas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_recommendations_created_at'), 'recommendations', ['created_at'], unique=False)
    op.create_index(op.f('ix_recommendations_id'), 'recommendations', ['id'], unique=False)
    op.create_index(op.f('ix_recommendations_parking_area_id'), 'recommendations', ['parking_area_id'], unique=False)
    op.create_table('sensors',
    sa.Column('serial_number', sa.String(length=100), nullable=False),
    sa.Column('sensor_type', sa.Enum('CO', 'CO2', 'NO2', 'SO2', 'NH3', 'H2S', 'METHANE', 'LPG', 'SMOKE', 'PM25', 'PM10', 'TEMPERATURE', 'HUMIDITY', 'WIND_SPEED', 'WIND_DIRECTION', name='sensortype'), nullable=False),
    sa.Column('parking_area_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.Enum('ONLINE', 'OFFLINE', 'FAULTY', 'CALIBRATION_NEEDED', name='sensorstatus'), nullable=False),
    sa.Column('battery_level', sa.Float(), nullable=False),
    sa.Column('health_score', sa.Float(), nullable=False),
    sa.Column('failure_probability', sa.Float(), nullable=False),
    sa.Column('last_calibrated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('firmware_version', sa.String(length=50), nullable=True),
    sa.Column('install_location', sa.String(length=255), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['parking_area_id'], ['parking_areas.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('serial_number')
    )
    op.create_index(op.f('ix_sensors_id'), 'sensors', ['id'], unique=False)
    op.create_table('vehicles',
    sa.Column('plate_number', sa.String(length=20), nullable=False),
    sa.Column('vehicle_type', sa.String(length=50), nullable=False),
    sa.Column('driver_name', sa.String(length=255), nullable=True),
    sa.Column('parking_area_id', sa.UUID(), nullable=True),
    sa.Column('status', sa.Enum('ENTERED', 'PARKED', 'EXITED', name='vehiclestatus'), nullable=False),
    sa.Column('entered_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('parked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('exited_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['parking_area_id'], ['parking_areas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_vehicles_id'), 'vehicles', ['id'], unique=False)
    op.create_index(op.f('ix_vehicles_plate_number'), 'vehicles', ['plate_number'], unique=False)
    op.create_table('gas_readings',
    sa.Column('sensor_id', sa.UUID(), nullable=False),
    sa.Column('parking_area_id', sa.UUID(), nullable=False),
    sa.Column('co', sa.Float(), nullable=True),
    sa.Column('co2', sa.Float(), nullable=True),
    sa.Column('no2', sa.Float(), nullable=True),
    sa.Column('so2', sa.Float(), nullable=True),
    sa.Column('nh3', sa.Float(), nullable=True),
    sa.Column('h2s', sa.Float(), nullable=True),
    sa.Column('methane', sa.Float(), nullable=True),
    sa.Column('lpg', sa.Float(), nullable=True),
    sa.Column('smoke', sa.Float(), nullable=True),
    sa.Column('pm25', sa.Float(), nullable=True),
    sa.Column('pm10', sa.Float(), nullable=True),
    sa.Column('temperature', sa.Float(), nullable=True),
    sa.Column('humidity', sa.Float(), nullable=True),
    sa.Column('wind_speed', sa.Float(), nullable=True),
    sa.Column('wind_direction', sa.Float(), nullable=True),
    sa.Column('recorded_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['parking_area_id'], ['parking_areas.id'], ),
    sa.ForeignKeyConstraint(['sensor_id'], ['sensors.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_gas_readings_id'), 'gas_readings', ['id'], unique=False)
    op.create_index('ix_gas_readings_parking_time', 'gas_readings', ['parking_area_id', 'recorded_at'], unique=False)
    op.create_index(op.f('ix_gas_readings_recorded_at'), 'gas_readings', ['recorded_at'], unique=False)
    op.create_index('ix_gas_readings_sensor_time', 'gas_readings', ['sensor_id', 'recorded_at'], unique=False)
    op.create_table('maintenance_logs',
    sa.Column('sensor_id', sa.UUID(), nullable=False),
    sa.Column('event_type', sa.String(length=50), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('performed_by', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['sensor_id'], ['sensors.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_maintenance_logs_id'), 'maintenance_logs', ['id'], unique=False)
    op.create_table('alerts',
    sa.Column('parking_area_id', sa.UUID(), nullable=False),
    sa.Column('triggered_by_reading_id', sa.UUID(), nullable=True),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('message', sa.String(length=1000), nullable=False),
    sa.Column('severity', sa.Enum('INFO', 'WARNING', 'CRITICAL', name='alertseverity'), nullable=False),
    sa.Column('status', sa.Enum('OPEN', 'ACKNOWLEDGED', 'RESOLVED', name='alertstatus'), nullable=False),
    sa.Column('channels', sa.ARRAY(sa.String()), nullable=False),
    sa.Column('gas_type', sa.String(length=50), nullable=True),
    sa.Column('measured_value', sa.Float(), nullable=True),
    sa.Column('threshold_value', sa.Float(), nullable=True),
    sa.Column('acknowledged_by_id', sa.UUID(), nullable=True),
    sa.Column('acknowledged_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['acknowledged_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['parking_area_id'], ['parking_areas.id'], ),
    sa.ForeignKeyConstraint(['triggered_by_reading_id'], ['gas_readings.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_alerts_created_at'), 'alerts', ['created_at'], unique=False)
    op.create_index(op.f('ix_alerts_id'), 'alerts', ['id'], unique=False)
    op.create_index(op.f('ix_alerts_parking_area_id'), 'alerts', ['parking_area_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_alerts_parking_area_id'), table_name='alerts')
    op.drop_index(op.f('ix_alerts_id'), table_name='alerts')
    op.drop_index(op.f('ix_alerts_created_at'), table_name='alerts')
    op.drop_table('alerts')
    op.drop_index(op.f('ix_maintenance_logs_id'), table_name='maintenance_logs')
    op.drop_table('maintenance_logs')
    op.drop_index('ix_gas_readings_sensor_time', table_name='gas_readings')
    op.drop_index(op.f('ix_gas_readings_recorded_at'), table_name='gas_readings')
    op.drop_index('ix_gas_readings_parking_time', table_name='gas_readings')
    op.drop_index(op.f('ix_gas_readings_id'), table_name='gas_readings')
    op.drop_table('gas_readings')
    op.drop_index(op.f('ix_vehicles_plate_number'), table_name='vehicles')
    op.drop_index(op.f('ix_vehicles_id'), table_name='vehicles')
    op.drop_table('vehicles')
    op.drop_index(op.f('ix_sensors_id'), table_name='sensors')
    op.drop_table('sensors')
    op.drop_index(op.f('ix_recommendations_parking_area_id'), table_name='recommendations')
    op.drop_index(op.f('ix_recommendations_id'), table_name='recommendations')
    op.drop_index(op.f('ix_recommendations_created_at'), table_name='recommendations')
    op.drop_table('recommendations')
    op.drop_index(op.f('ix_predictions_parking_area_id'), table_name='predictions')
    op.drop_index(op.f('ix_predictions_id'), table_name='predictions')
    op.drop_index(op.f('ix_predictions_generated_at'), table_name='predictions')
    op.drop_table('predictions')
    op.drop_index(op.f('ix_audit_logs_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_created_at'), table_name='audit_logs')
    op.drop_table('audit_logs')
    op.drop_index(op.f('ix_analytics_rollups_parking_area_id'), table_name='analytics_rollups')
    op.drop_index(op.f('ix_analytics_rollups_id'), table_name='analytics_rollups')
    op.drop_table('analytics_rollups')
    op.drop_index(op.f('ix_weather_records_recorded_at'), table_name='weather_records')
    op.drop_index(op.f('ix_weather_records_id'), table_name='weather_records')
    op.drop_table('weather_records')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_parking_areas_id'), table_name='parking_areas')
    op.drop_table('parking_areas')
    # ### end Alembic commands ###
