"""add push token and alert notification logs

Revision ID: f2258faf15fa
Revises: 0002
Create Date: 2026-07-17 11:56:42.313502

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0003'
down_revision: Union[str, None] = '0002'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('alert_notification_logs',
    sa.Column('alert_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('channel', sa.String(length=20), nullable=False),
    sa.Column('recipient_target', sa.String(length=255), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['alert_id'], ['alerts.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_alert_notification_logs_alert_id'), 'alert_notification_logs', ['alert_id'], unique=False)
    op.create_index(op.f('ix_alert_notification_logs_created_at'), 'alert_notification_logs', ['created_at'], unique=False)
    op.create_index(op.f('ix_alert_notification_logs_id'), 'alert_notification_logs', ['id'], unique=False)
    op.add_column('users', sa.Column('push_token', sa.String(length=512), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'push_token')
    op.drop_index(op.f('ix_alert_notification_logs_id'), table_name='alert_notification_logs')
    op.drop_index(op.f('ix_alert_notification_logs_created_at'), table_name='alert_notification_logs')
    op.drop_index(op.f('ix_alert_notification_logs_alert_id'), table_name='alert_notification_logs')
    op.drop_table('alert_notification_logs')
    # ### end Alembic commands ###
