"""add camera frame analyses

Revision ID: 3ec3c7448a0c
Revises: 0003
Create Date: 2026-07-20 07:56:23.564945

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '0004'
down_revision: Union[str, None] = '0003'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('camera_frame_analyses',
    sa.Column('parking_area_id', sa.UUID(), nullable=False),
    sa.Column('vehicle_count', sa.Integer(), nullable=False),
    sa.Column('person_count', sa.Integer(), nullable=False),
    sa.Column('detected_objects', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('registered_parked_count', sa.Integer(), nullable=False),
    sa.Column('unauthorized_parking_suspected', sa.Boolean(), nullable=False),
    sa.Column('smoke_detected', sa.Boolean(), nullable=False),
    sa.Column('smoke_confidence', sa.Float(), nullable=False),
    sa.Column('fire_detected', sa.Boolean(), nullable=False),
    sa.Column('fire_confidence', sa.Float(), nullable=False),
    sa.Column('alert_id', sa.UUID(), nullable=True),
    sa.Column('model_name', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['alert_id'], ['alerts.id'], ),
    sa.ForeignKeyConstraint(['parking_area_id'], ['parking_areas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_camera_frame_analyses_created_at'), 'camera_frame_analyses', ['created_at'], unique=False)
    op.create_index(op.f('ix_camera_frame_analyses_id'), 'camera_frame_analyses', ['id'], unique=False)
    op.create_index(op.f('ix_camera_frame_analyses_parking_area_id'), 'camera_frame_analyses', ['parking_area_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_camera_frame_analyses_parking_area_id'), table_name='camera_frame_analyses')
    op.drop_index(op.f('ix_camera_frame_analyses_id'), table_name='camera_frame_analyses')
    op.drop_index(op.f('ix_camera_frame_analyses_created_at'), table_name='camera_frame_analyses')
    op.drop_table('camera_frame_analyses')
    # ### end Alembic commands ###
